const GET_CURRENT_TIME = 'GET_CURRENT_TIME';
const ADD_USER = 'ADD_USER';
const REMOVE_USER = 'REMOVE_USER';
const RESET_USERS_LIST = 'RESET_USERS_LIST';

export default {
    GET_CURRENT_TIME,
    ADD_USER,
    REMOVE_USER,
    RESET_USERS_LIST,
};
